### ISSUE TITLE
Unable to find class : InfluxDBResultMapper in lower version of android

### ISSUE THREAD

**Issue by sqlharsh** [influxdata/influxdb-java#620]
I am fetching data using influx-java dependency, It's working perfectly in android os 8.0 but throws ClassNotFoundException exception in android os 7.1.1 , 6.0, etc. I found one of the class: DateTimeFormatterBuilder is newly added in Java_8 , since I am using java_8 it should work on any os versions. The error I got is :

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatterBuilder;
        at org.influxdb.impl.InfluxDBResultMapper.<clinit>(InfluxDBResultMapper.java:61)
        at com.impelzone.viewmodel.DeviceDetailViewmodel$fetchDeviceData$1$1.run(DeviceDetailViewmodel.kt:162)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.format.DateTimeFormatterBuilder" on path: DexPathList[[zip file "/data/app/com.Impelzone-2/base.apk"],nativeLibraryDirectories=[/data/app/com.Impelzone-2/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.influxdb.impl.InfluxDBResultMapper.<clinit>(InfluxDBResultMapper.java:61) 
        at com.impelzone.viewmodel.DeviceDetailViewmodel$fetchDeviceData$1$1.run(DeviceDetailViewmodel.kt:162) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6165) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)  
```

I am using this dependency : org.influxdb:influxdb-java:2.15

@fmachado , Please help me out of this .

**Comment by fmachado** [comment]
@sqlharsh apologies for the loooong delay on my answer.

Unfortunately `influxdb-java` won't work on Android 7 because `DateTimeFormatterBuilder` was added on [API level 26](https://developer.android.com/reference/java/time/format/DateTimeFormatterBuilder) (i.e. Android 8).
